backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow
media_folder: "assets/images/cms" # Media files will be stored in the repo under src/assets/images/posts
public_folder: "/assets/images/cms" # The src attribute for uploaded media will begin with assets/images/posts

collections:
- name: "estrategia"
    label: "Estrategia 2022-2025"
    folder: "src/cms/administracion"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Título" }
      - { name: "link", label: "Enlace a Documento" }
  - name: "administracion" # Used in routes, e.g., /admin/collections/podcast
    label: "Administracion" # Used in the UI
    folder: "src/cms/administracion" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Documento" }
      - { name: "categoria", label: "categoria" }
      - { name: "prioridad", label: "Prioridad" }
      - { name: "estado", label: "Estado", widget: "select", options: ['Por Empezar', 'En Progreso', 'Finalizado'], multiple: false }
      - { name: "link", label: "Link de Descarga" }
  - name: "indicadores"
    label: "Indicadores"
    folder: "src/cms/indicadores"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Indicador" }
      - {
          name: "programa",
          label: "Programa",
          widget: "select",
          options:
            [
              "Innovación en Gobierno",
              "Innovación Social",
              "Fortalecimiento de espacios cívicos",
              "Auditoria Social",
            ],
          multiple: false,
        }
      - { name: "descripcion", label: "Descripcion", widget: "text" }
      - { name: "resultadototal", label: "Resultado Total" }
      - { name: "restante", label: "Restante" }
      - { name: "meta", label: "Meta 2025" }
  - name: "proyectos"
    label: "Proyectos"
    folder: "src/cms/proyectos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Proyecto" }
      - {
          name: "programa",
          label: "Programa",
          widget: "select",
          options:
            [
              "Innovación en Gobierno",
              "Innovación Social",
              "Fortalecimiento de espacios cívicos",
              "Auditoria Social",
            ],
          multiple: false,
        }
      - { name: "descripcion", label: "Descripcion", widget: "text" }
      - { name: "tdc", label: "TdC" }
      - { name: "tematica", label: "Tematica" }
      - { name: "fase", label: "Fase" }
      - { name: "ano", label: "Año" }
      - {
          name: "fechaInicio",
          label: "FechaInicio",
          widget: "date",
          format: "DD MM YYYY",
        }
      - {
          name: "fechaCierre",
          label: "FechaCierre",
          widget: "date",
          format: "DD MM YYYY",
        }
      - { name: "estado", label: "Estado", widget: "select", options: ['Por Empezar', 'En Progreso', 'Finalizado'], multiple: false }
      - { name: "progreso", label: "Progreso" }
      - { name: "actividades", label: "Actividades" }
      - { name: "ubicacion", label: "Ubicación" }
      - { name: "enlaceProducto", label: "Enlace del Producto" }
      - {
          name: "logoProyecto",
          label: "Logo Proyecto",
          hint: "Direccion url de la imagen",
        }
      - {
          name: "logoProyecto80",
          label: "Logo Proyecto 80 x 80",
          hint: "Direccion url de la imagen pequeña desplegada en preview",
        }
      - { name: "EnlaceReportes", label: "Enlace Reportes" }
      - {
          name: "ods",
          label: "ODS",
          widget: "select",
          options:
            [
              "1",
              "2",
              "3",
              "4",
              "5",
              "6",
              "7",
              "8",
              "9",
              "10",
              "11",
              "12",
              "13",
              "14",
              "15",
              "16",
              "17",
              "18",
            ],
        }
  - name: "actividades"
    label: "Actividades"
    folder: "src/cms/actividades"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Actividad" }
      - { name: "proyecto", label: "Proyecto",  widget: "relation", collection: "proyectos", searchFields: ["title"], valueField: "title", multiple: false}
      - {
          name: "programa",
          label: "Programa",
          widget: "select",
          options:
            [
              "Innovación en Gobierno",
              "Innovación Social",
              "Fortalecimiento de espacios cívicos",
              "Auditoria Social",
            ],
          multiple: false,
        }
      - { name: "tematica", label: "Temática"}
      - { name: "descripcion", label: "Descripción", widget: "text"}
      - { name: "estado", label: "Estado", widget: "select", options: ['Por Empezar', 'En Progreso', 'Finalizado'], multiple: false}
      - {
          name: "fechaInicio",
          label: "FechaInicio",
          widget: "date",
          format: "DD MM YYYY",
        }
      - {
          name: "fechaCierre",
          label: "FechaCierre",
          widget: "date",
          format: "DD MM YYYY",
        }
      - { name: "enlace", label: "Enlace de Actividad"}
  - name: "financiamiento"
    label: "Financiamiento"
    folder: "src/cms/financiamiento"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Financiamiento" }
      - { name: "ano", label: "Año"}
      - { name: "donante", label: "Donante"}
      - { name: "enlacedonante", label: "Enlace del Donante"}
      - { name: "proyecto", label: "Proyecto",  widget: "relation", collection: "proyectos", searchFields: ["title"], valueField: "title", multiple: false}
      - { name: "enlaceproyecto", label: "Enlace del Proyecto"}
      - { name: "enlaceconvenio", label: "Enlace del Convenio"}
      - { name: "tipodonacion", label: "Tipo de Donacion"}
      - { name: "monto", label: "Monto", widget: "number", value_type: "float"}
      - {
          name: "highlight",
          label: "Highlight",
          widget: "boolean",
          default: false,
        }
  - name: "monitoreo"
    label: "Monitoreo"
    folder: "src/cms/monitoreo"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    fields: # The fields for each document, usually in front matter
      - { name: "title", label: "Monitoreo" }
      - {
          name: "programa",
          label: "Programa",
          widget: "select",
          options:
            [
              "Innovación en Gobierno",
              "Innovación Social",
              "Fortalecimiento de espacios cívicos",
              "Auditoria Social",
            ],
          multiple: false,
        }
      - { name: "proyecto", label: "Proyecto",  widget: "relation", collection: "proyectos", searchFields: ["title"], valueField: "title", multiple: false}
      - { name: "fase", label: "Fase"}
      - { name: "ano", label: "Año"}
      - { name: "estado", label: "Estado"}
      - {
          name: "fechaInicio",
          label: "FechaInicio",
          widget: "date",
          format: "DD MM YYYY",
        }
      - {
          name: "fechaCierre",
          label: "FechaCierre",
          widget: "date",
          format: "DD MM YYYY",
        }
      - { name: "nombre", label: "Nombre"}
      - { name: "correo", label: "Correo"}
      - { name: "genero", label: "Género"}
      - { name: "edad", label: "edad", widget: "number", value_type: "int"}
      - { name: "academico", label: "Académico"}
      - { name: "sector", label: "Sector"}
  - name: "monitoreo"
    label: "Monitoreo"
    folder: "src/cms/monitoreo"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    identifier_field: comportamientos
    fields: # The fields for each document, usually in front matter
      - { name: "comportamientos", label: "Embed de Comportamientos", widget: "markdown" }
      - { name: "audiencia", label: "Embed de Audiencia", widget: "markdown" }
  - name: "reporteanual"
    label: "Reporte Anual"
    folder: "src/cms/reporte"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false # Disable the editor preview and use instead 'preview links'
    identifier_field: reporte
    fields: # The fields for each document, usually in front matter
      - { name: "reporte", label: "Enlace al reporte" }
      - { name: "instituciones", label: "Instituciones", hint: "Instituciones públicas con las que se colabora" }
      - { name: "organizaciones", label: "Organizaciones", hint: "Organizaciones con las que se colabora" }
      - { name: "cursos", label: "Cursos", hint: "Cursos de innovación" }
      - { name: "estudiantes", label: "Estudiantes" }
      - { name: "participantes", label: "Participantes", hint: "Participantes en procesos de Co-Creación" }
      - { name: "publicacionesyreportes", label: "Publicaciones y Reportes"}